### ISSUE TITLE
Circuitry vs Circuity

### ISSUE THREAD

**Issue by kuanb** [rmcarder/raleighparks#1]
I stumbled on this as I was sent to https://github.com/ccusa/Disaster_Vulnerability_Map just a moment ago.

Just thought I would make a note that, in your README, you identify "Circuitry" as a measure or focus of this project. I think the term you were intending was "Circuity". See definition [here](https://en.wikibooks.org/wiki/Transportation_Geography_and_Network_Science/Circuity).

**Comment by rmcarder** [comment]
You're right. Thank you! I've changed hopefully all references to it.
